### ISSUE TITLE
AttributeError: Can't get attribute 'FlattenedLoss'

### ISSUE THREAD

**Issue by sinemkulac** [brunosan/iris-ai#3]
I got error when I run server.py in iris-GCE. I am not sure but issue may due to different version , which version of fastai do you use ?
fastai 2.1.8
torch  1.7.1
torchvision 0.8.2
> (myenv) E:\user\Notebooks\AP\iris-ai\iris-GCE\app>python server.py serve
> Traceback (most recent call last):
>   File "server.py", line 107, in<module>
>     learn = loop.run_until_complete(asyncio.gather(*tasks))[0]
>   File "E:\user\anaconda\envs\myenv\lib\asyncio\base_events.py", line 573, in run_until_complete
>     return future.result()
>   File "server.py", line 76, in setup_learner
>     learn = load_learner(path/model_file_name)
>   File "E:\user\anaconda\envs\myenv\lib\site-packages\fastai\learner.py", line 553, in load_learner
>     res = torch.load(fname, map_location='cpu' if cpu else None)
>   File "E:\user\anaconda\envs\myenv\lib\site-packages\torch\serialization.py", line 595, in load
>     return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
>   File "E:\user\anaconda\envs\myenv\lib\site-packages\torch\serialization.py", line 774, in _legacy_load
>     result = unpickler.load()
> AttributeError: Can't get attribute 'FlattenedLoss' on <module 'fastai.layers' from 'E:\\user\\anaconda\\envs\\myenv\\lib\\site-packages\\fastai\\layers.py'>

**Comment by zlh1992** [comment]
Is there any solution of this problem?
I meet the same problem 
torch 1.5.1
